name: Continuous Integration

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: ${{ matrix.config.shell }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux GCC
            os: ubuntu-latest
            compiler: gcc
            shell: bash

          - name: macOS Clang
            os: macos-latest
            compiler: clang
            shell: bash

          - name: macOS x86 Clang
            os: macos-15-intel
            compiler: clang
            shell: bash


    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-net-dev \
            libpng-dev \
            libsamplerate0-dev \
            libfluidsynth-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install \
            automake \
            sdl2 \
            sdl2_mixer \
            sdl2_net \
            libpng \
            libsamplerate \
            fluid-synth

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: Configure
        env:
          CC: ${{ matrix.config.compiler }}
        working-directory: satellite/doom
        run: |
          ./autogen.sh

      - name: Build
        working-directory: satellite/doom
        run: make -j4

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.x'

      - name: Test
        run: |
          pip install pyyaml
          PREFIX=`sed -n '/PROGRAM_PREFIX/p' satellite/doom/config.h | cut -d '"' -f 2`
          make -j4 -C quickcheck check SOURCE_PORT=$PWD/satellite/doom/src/${PREFIX}doom

